server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:12100/smart_training1
    username: bunny
    password: bunny
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com.proshine.training: debug
app:
  encryption:
    key: "dGhpcyBpcyBhIHNlY3VyZSByYW5kb20gbG9uZyBrZXk"
