spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_training?serverTimezone=UTC&useSSL=false
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
jwt:
  secret: "replace_with_32_chars_random_string________________"
  expiration: 86400000
